=== 120534/deegree3/deegree-datastores/deegree-tilestores/deegree-tilestore-remotewms/src/main/resources/META-INF/schemas/datasource/tile/remotewms/3.2.0/remotewms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:md="http://www.deegree.org/metadata/spatial"
  targetNamespace="http://www.deegree.org/datasource/tile/remotewms" elementFormDefault="qualified"
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">

  <import namespace="http://www.deegree.org/metadata/spatial" schemaLocation="http://schemas.deegree.org/commons/spatialmetadata/3.1.0/spatialmetadata.xsd" />

  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.tile.persistence.remotewms.jaxb" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>

  <element name="RemoteWMSTileStore">
    <annotation>
      <documentation>TileStore that is backed by a remote WMS instance.</documentation>
      <appinfo>
        <jaxb:class name="RemoteWMSTileStoreJAXB" />
      </appinfo>
    </annotation>
    <complexType>
      <sequence>
        <element name="TileMatrixSet" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <element name="RemoteWMSId" type="string">
                <annotation>
                  <documentation>Id of the remote OWS to connect to (must be a WMS instance)</documentation>
                </annotation>
              </element>
              <element ref="md:CRS">
                <annotation>
                  <documentation>CRS for querying the remote service as well as the resulting tiles</documentation>
                </annotation>
              </element>
              <element ref="md:Envelope" minOccurs="0">
                <annotation>
                  <documentation>Envelope of the tiled area, if omitted, the bounding box reported for the WMS layers
                    will be
                    used
                  </documentation>
                </annotation>
              </element>
              <element name="RequestParams">
                <annotation>
                  <documentation>WMS request parameters</documentation>
                </annotation>
                <complexType>
                  <sequence>
                    <element name="Layers" type="string">
                      <annotation>
                        <documentation>Comma-separated list of layer names</documentation>
                      </annotation>
                    </element>
                    <element name="Styles" type="string" minOccurs="0">
                      <annotation>
                        <documentation>Comma-separated list of styles</documentation>
                      </annotation>
                    </element>
                    <element name="Format" type="string">
                      <annotation>
                        <documentation>Image format</documentation>
                      </annotation>
                    </element>
                  </sequence>
                </complexType>
              </element>

              <element name="TilePyramid">
                <complexType>
                  <sequence>
                    <element name="Identifier" type="string">
                      <annotation>
                        <documentation>The identifier of the tile matrix set</documentation>
                      </annotation>
                    </element>
                    <element name="TileWidth" type="positiveInteger">
                      <annotation>
                        <documentation>Width of a single tile in pixels</documentation>
                      </annotation>
                    </element>
                    <element name="TileHeight" type="positiveInteger">
                      <annotation>
                        <documentation>Height of a single tile in pixels</documentation>
                      </annotation>
                    </element>
                    <element name="MinScaleDenominator" type="double">
                      <annotation>
                        <documentation>First scale level (base of the pyramid), scales of other levels are generated by
                          subsequent division by two
                        </documentation>
                      </annotation>
                    </element>
                    <element name="NumLevels" type="positiveInteger">
                      <annotation>
                        <documentation>Number of scale levels</documentation>
                      </annotation>
                    </element>
                    <element name="ImageFormat" type="string" minOccurs="0">
                      <annotation>
                        <documentation>Output image format. Default is the format from the WMS (it's more performant).
                        </documentation>
                      </annotation>
                    </element>
                  </sequence>
                </complexType>
              </element>
            </sequence>
          </complexType>
        </element>
      </sequence>
      <attribute name="configVersion" use="required" fixed="3.2.0" />
    </complexType>
  </element>

</schema>

=== 120534/deegree3/deegree-datastores/deegree-tilestores/deegree-tilestore-remotewms/src/test/resources/org/deegree/tile/persistence/remotewms/workspace/datasources/tile/tiles26912.xml
<?xml version="1.0"?>
<RemoteWMSTileStore xmlns="http://www.deegree.org/datasource/tile/remotewms" xmlns:md="http://www.deegree.org/metadata/spatial"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.deegree.org/datasource/tile/remotewms http://schemas.deegree.org/datasource/tile/remotewms/3.2.0/remotewms.xsd"
  configVersion="3.2.0">

  <TileMatrixSet>

    <!-- [1]: Id of the remote OWS to connect to (must be a WMS instance) -->
    <RemoteWMSId>utah-wms</RemoteWMSId>

    <!-- [1]: CRS for querying the remote service as well as the resulting tiles -->
    <md:CRS>EPSG:26912</md:CRS>

    <!-- [1]: WMS request parameters -->
    <RequestParams>
      <!-- [1] Comma-separated list of layer names -->
      <Layers>CountyBoundaries,CountyNames</Layers>
      <!-- [0..1] Comma-separated list of styles -->
      <Styles>default,default</Styles>
      <!-- [1] Image format -->
      <Format>image/png</Format>
    </RequestParams>

    <!-- [1]: Geometry of the tile pyramid -->
    <TilePyramid>
      <Identifier>tiles26912</Identifier>
      <!-- [1]: Width of a single tile in pixels -->
      <TileWidth>256</TileWidth>
      <!-- [1]: Height of a single tile in pixels -->
      <TileHeight>256</TileHeight>
      <!-- [1]: First scale level (base of the pyramid), scales of other levels are generated by subsequent division by two -->
      <MinScaleDenominator>1000</MinScaleDenominator>
      <!-- [1]: Number of scale levels -->
      <NumLevels>10</NumLevels>
    </TilePyramid>
  </TileMatrixSet>
</RemoteWMSTileStore>
