=== 120534/deegree3/deegree-client/deegree-mdeditor/resources/schema/codelistConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.deegree.org/igeoportal" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.deegree.org/igeoportal" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:import />
    <xs:element name="CodeListConfiguration">
        <xs:annotation>
            <xs:documentation>a list of code lists</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CodeList" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CodeList">
        <xs:annotation>
            <xs:documentation>a list of static values</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Code" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>the id to identify the codlist </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="Code">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="value" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>the value of the code</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="label" type="xs:string" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the label of the code displayed in the selection list, if this element is
                            missing, the value </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 120534/deegree3/deegree-client/deegree-mdeditor/src/main/webapp/WEB-INF/conf/mdeditor/exampleCodeListConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!--XML-Beispieldatei von XMLSpy generiert v2008 rel. 2 sp2 (http://www.altova.com)-->
<CodeListConfiguration xsi:schemaLocation="http://www.deegree.org/igeoportal schema/codelistConfiguration.xsd"
    xmlns="http://www.deegree.org/igeoportal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <CodeList id="keyword">
        <Code>
            <value>Abitur</value>
            <label>Abitur</label>
        </Code>
        <Code>
            <value>single</value>
            <label>Single</label>
        </Code>
        <Code>
            <value>steuern</value>
            <label>Steuern</label>
        </Code>
        <Code>
            <value>zentren</value>
            <label>Zentren</label>
        </Code>
    </CodeList>
    <CodeList id="theme">
        <Code>
            <value>society</value>
            <label>society</label>
        </Code>
        <Code>
            <value>biota</value>
            <label>biota</label>
        </Code>
        <Code>
            <value>farming</value>
            <label>farming</label>
        </Code>
        <Code>
            <value>oceans</value>
            <label>oceans</label>
        </Code>
    </CodeList>
    <CodeList id="hierarchylevel">
        <Code>
            <value>dataset</value>
            <label>Datensatz</label>
        </Code>
        <Code>
            <value>service</value>
            <label>Service</label>
        </Code>
    </CodeList>
    <CodeList id="countries">
        <Code>
            <value>brd</value>
            <label>Bundesrepublik</label>
        </Code>
        <Code>
            <value>NRW</value>
            <label>Nordrhein-Westfalen</label>
        </Code>
        <Code>
            <value>bremen</value>
            <label>Bremen</label>
        </Code>
        <Code>
            <value>saarland</value>
            <label>Saarland</label>
        </Code>
        <Code>
            <value>berlin</value>
            <label>Berlin</label>
        </Code>
        <Code>
            <value>niedersachsen</value>
            <label>Niedersachsen</label>
        </Code>
    </CodeList>
    <CodeList id="roleCode">
        <Code>
            <value>resourceProvider</value>
            <label>Anbieter</label>
        </Code>
        <Code>
            <value>custodian</value>
            <label>Verwalter</label>
        </Code>
        <Code>
            <value>owner</value>
            <label>Eigent√ºmer</label>
        </Code>
        <Code>
            <value>user</value>
            <label>Nutzer</label>
        </Code>
        <Code>
            <value>distributor</value>
            <label>Vertrieb</label>
        </Code>
        <Code>
            <value>originator</value>
            <label>Urheber</label>
        </Code>
        <Code>
            <value>pointOfContact</value>
            <label>Ansprechpartner</label>
        </Code>
        <Code>
            <value>principalInvestigator</value>
            <label>Projektleitung</label>
        </Code>
        <Code>
            <value>processor</value>
            <label>Bearbeiter</label>
        </Code>
        <Code>
            <value>publisher</value>
            <label>Herausgeber</label>
        </Code>
        <Code>
            <value>author</value>
            <label>Autor</label>
        </Code>
    </CodeList>
</CodeListConfiguration>
