=== 120534/deegree3/deegree-client/deegree-mdeditor/resources/schema/formConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.deegree.org/igeoportal" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.deegree.org/igeoportal" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:import />
    <xs:element name="FormConfiguration">
        <xs:annotation>
            <xs:documentation>root element describing the configuration of the gui</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="layoutType" />
                <xs:element ref="FormGroup" maxOccurs="unbounded" />
                <xs:element ref="CodeList" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="FormGroup">
        <xs:annotation>
            <xs:documentation>groups a list of FormElements, the sequence of the elements in the gui is equal to the
                order of occurence in the configuration</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="label" type="xs:string" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the label is displayed as menu, tab entry or tooltip, dependent on the layout
                            type</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="title" type="xs:string" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the title is displayed as title in the form group block</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="FormElement" maxOccurs="unbounded" />
                    <xs:element ref="FormGroup" maxOccurs="unbounded" />
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="FormElement" type="FormElement_Type" abstract="true" />
    <xs:complexType name="FormElement_Type" abstract="true">
        <xs:annotation>
            <xs:documentation>describes a single form element like a text input field or a select list
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0" />
            <xs:element name="help" type="xs:string" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="id" use="required" />
        <xs:attribute name="visible" type="xs:boolean" default="true" />
        <xs:attribute name="isIdentifier" type="xs:boolean" default="false" />
    </xs:complexType>
    <xs:element name="InputFormElement" type="InputFormElement" substitutionGroup="FormElement" />
    <xs:complexType name="InputFormElement">
        <xs:annotation>
            <xs:documentation>describes a single input element, like a text field</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="FormElement_Type">
                <xs:sequence>
                    <xs:element ref="inputType" />
                    <xs:element name="defaultValue" type="xs:string" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>the default value for this input field. The entered value must match to
                                the inputType and the validation, if noted.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element ref="Validation" minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="SelectFormElement" type="SelectFormElement" substitutionGroup="FormElement" />
    <xs:complexType name="SelectFormElement">
        <xs:annotation>
            <xs:documentation>describes a form element where selections can be made</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="FormElement_Type">
                <xs:sequence>
                    <xs:element ref="selectType" />
                    <xs:choice>
                        <xs:sequence>
                            <xs:element name="referenceToGroup" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>the id of the configured group element, which values should be
                                        selectable by this list</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="showAsLink" type="xs:boolean" default="true">
                                                <xs:annotation>
                                                    <xs:documentation>indicates if the form group should be accessible by a
                                                        link</xs:documentation>
                                                </xs:annotation>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="referenceText" minOccurs="0" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation></xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                        <xs:element name="referenceToCodeList" type="xs:string" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>the id of the configured code list, which values should be selectable
                                    by this list</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:choice>
                    <xs:element name="selectedValue" type="xs:string" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>if a referenceToCodeList is set, the value of the code to select can be
                                entered, can be a comma seperated list, if select type is 'many'</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="ReferencedFormElement" type="ReferencedFormElement" substitutionGroup="FormElement" />
    <xs:complexType name="ReferencedFormElement">
        <xs:annotation>
            <xs:documentation>describes a single element, described by a JSF bean</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="FormElement_Type">
                <xs:sequence>
                    <xs:element name="bean-name" type="xs:string">
                        <xs:annotation>
                            <xs:documentation>name of the bean (e.g. generateIdBean) which must be a subclass of
                                ReferencedElementBean. This bean must have a methode returning the view of this
                                component</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="Validation">
        <xs:annotation>
            <xs:documentation>specifies the given input type</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="length" type="xs:integer" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the length of the string for inputType 'string'</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="timestampPattern" type="xs:string" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the pattern of the timestamp for inputType 'date'</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="minValue" type="xs:double" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the min value for inputType 'int' or 'double'</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="maxValue" type="xs:double" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the max value for inputType 'date' or 'double'</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="CodeList">
        <xs:annotation>
            <xs:documentation>a list of static values, which can be referenced by a SelectFormElement</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Code" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="Code">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="value" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>the value of the code</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="label" type="xs:string" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>the label of the code displayed in the selection list</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- enumerations -->
    <xs:element name="inputType">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="text" />
                <xs:enumeration value="textarea" />
                <xs:enumeration value="timestamp" />
                <xs:enumeration value="int" />
                <xs:enumeration value="double" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="selectType">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="one" />
                <xs:enumeration value="many" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="layoutType">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="wizard" />
                <xs:enumeration value="tab" />
                <xs:enumeration value="menu" />
                <xs:enumeration value="accordion" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== 120534/deegree3/uncoupled/deegree-mdeditor/src/test/resources/org/deegree/client/mdeditor/configuration/globalConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!--XML-Beispieldatei von XMLSpy generiert v2008 rel. 2 sp2 (http://www.altova.com)-->
<FormConfiguration xsi:schemaLocation="http://www.deegree.org/igeoportal schema/formConfiguration.xsd"
    xmlns="http://www.deegree.org/igeoportal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
    <layoutType>tab</layoutType>
    
    <FormGroup id="ContactFormGroup">
        <label>Kontakt</label>
        <title>Kontaktdaten</title>
        <InputFormElement id="KtextName">
            <label>Name (Person):</label>
            <inputType>text</inputType>
        </InputFormElement>
        <InputFormElement id="KtextOrga">
            <label>Organisation:</label>
            <inputType>text</inputType>
        </InputFormElement>
        <SelectFormElement id="KselectRole">
            <label>Rolle/Funktion:</label>
            <selectType>one</selectType>
            <referenceToCodeList>roleCode</referenceToCodeList>
        </SelectFormElement>
        <FormGroup id="KSubFormGRoup">
            <title> Adresse:</title>
            <InputFormElement id="KStextStreet">
                <label>Strasse/Hausnummer:</label>
                <inputType>text</inputType>
            </InputFormElement>
            <InputFormElement id="KStextCity">
                <label>Stadt:</label>
                <inputType>text</inputType>
            </InputFormElement>
            <InputFormElement id="KStextPLZ">
                <label>Postleitzahl:</label>
                <inputType>int</inputType>
                <Validation>
                    <minValue>10000</minValue>
                    <maxValue>99999</maxValue>
                </Validation>
            </InputFormElement>
            <InputFormElement id="KStextCountry">
                <label>Land:</label>
                <inputType>text</inputType>
            </InputFormElement>
        </FormGroup>
        <InputFormElement id="KtextPhone">
            <label>Telefonnummer:</label>
            <inputType>text</inputType>
        </InputFormElement>
        <InputFormElement id="KtextFax">
            <label>Fax-Nummer:</label>
            <inputType>text</inputType>
        </InputFormElement>
        <InputFormElement id="KtextEmail">
            <label>EMail-Adresse:</label>
            <inputType>text</inputType>
        </InputFormElement>
    </FormGroup>
</FormConfiguration>

=== 120534/deegree3/deegree-client/deegree-mdeditor/resources/exampleConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!--XML-Beispieldatei von XMLSpy generiert v2008 rel. 2 sp2 (http://www.altova.com)-->
<FormConfiguration xsi:schemaLocation="http://www.deegree.org/igeoportal schema/formConfiguration.xsd"
    xmlns="http://www.deegree.org/igeoportal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <layoutType>tab</layoutType>

    <FormGroup id="TestFormGroup">
        <label>Test</label>
        <title>Teste das Problem</title>
        <InputFormElement id="text5">
            <label>Problem:</label>
            <help>Die Hilfe für das Element text5 zum testen des Problems</help>
            <inputType>text</inputType>
        </InputFormElement>
        <SelectFormElement id="selectOneH" visible="true">
            <label>Hierarchieebene:</label>
            <selectType>many</selectType>
            <referenceToCodeList>countries</referenceToCodeList>
                <selectedValue>spain, greek</selectedValue>
        </SelectFormElement>
    </FormGroup>

    <FormGroup id="AllgFormGroup">
        <label>Angaben 2</label>
        <title>Allgemeine Angaben zum Metadatensatz</title>
        <SelectFormElement id="selectOne11" visible="true">
            <label>Hierarchieebene:</label>
            <selectType>one</selectType>
            <referenceToCodeList>hierarchylevel</referenceToCodeList>
            <selectedValue>service</selectedValue>
        </SelectFormElement>
        <InputFormElement id="text11">
            <label>Titel:</label>
            <inputType>text</inputType>
        </InputFormElement>
        <FormGroup id="FormGroup21">
            <title>Für die Metadaten zuständige Stelle/Person:</title>
            <InputFormElement id="text21">
                <label>Name (Person):</label>
                <inputType>text</inputType>
            </InputFormElement>
            <InputFormElement id="text31">
                <label>Organisation:</label>
                <inputType>text</inputType>
            </InputFormElement>
            <InputFormElement id="text14">
                <label>PLZ:</label>
                <inputType>int</inputType>
                <defaultValue>12345</defaultValue>
                <Validation>
                    <minValue>10000</minValue>
                    <maxValue>99999</maxValue>
                </Validation>
            </InputFormElement>
            <SelectFormElement id="selectOne12">
                <selectType>one</selectType>
                <referenceToCodeList>countries</referenceToCodeList>
            </SelectFormElement>
        </FormGroup>
    </FormGroup>

    <CodeList id="hierarchylevel">
        <Code>
            <value>dataset</value>
            <label>Datensatz</label>
        </Code>
        <Code>
            <value>service</value>
            <label>Service</label>
        </Code>
    </CodeList>
    <CodeList id="countries">
        <Code>
            <value>italy</value>
            <label>Italien</label>
        </Code>
        <Code>
            <value>spain</value>
            <label>Spanien</label>
        </Code>
        <Code>
            <value>greek</value>
            <label>Griechenland</label>
        </Code>
    </CodeList>
</FormConfiguration>

=== 120534/deegree3/deegree-client/deegree-mdeditor/src/test/resources/org/deegree/client/mdeditor/config/doubleIDTestConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!--XML-Beispieldatei von XMLSpy generiert v2008 rel. 2 sp2 (http://www.altova.com)-->
<FormConfiguration xsi:schemaLocation="http://www.deegree.org/igeoportal schema/formConfiguration.xsd"
    xmlns="http://www.deegree.org/igeoportal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <layoutType>tab</layoutType>

    <FormGroup id="FormGroup3">
        <label>Test</label>
        <title>Teste das Problem</title>
        <InputFormElement id="text5">
            <label>Problem:</label>
            <help>Die Hilfe für das Element text5 zum testen des Problems</help>
            <inputType>text</inputType>
        </InputFormElement>
        <InputFormElement id="text5">
            <label>Problem:</label>
            <help>Die Hilfe für das Element text5 zum testen des Problems</help>
            <inputType>text</inputType>
        </InputFormElement>
        <ReferencedFormElement id="ref" isIdentifier="true">
            <label>Id:</label>
            <help>Hiermit können sie eine eindeutige Id für den Datensatz generieren</help>
            <bean-name>generateIdBean</bean-name>
        </ReferencedFormElement>
    </FormGroup>

    <FormGroup id="FormGroup">
        <label>Allgemeine Angaben</label>
        <title>Allgemeine Angaben zum Metadatensatz</title>
        <SelectFormElement id="selectOne1" visible="true" required="true">
            <label>Hierarchieebene:</label>
            <selectType>one</selectType>
            <referenceToCodeList>hierarchylevel</referenceToCodeList>
        </SelectFormElement>
        <InputFormElement id="text1">
            <label>Titel:</label>
            <inputType>text</inputType>
        </InputFormElement>
        <FormGroup id="FormGroup11">
            <title>Für die Metadaten zuständige Stelle/Person:</title>
            <InputFormElement id="text2">
                <label>Name (Person):</label>
                <inputType>text</inputType>
            </InputFormElement>
            <InputFormElement id="text3">
                <label>Organisation:</label>
                <inputType>text</inputType>
            </InputFormElement>
            <InputFormElement id="text4">
                <label>PLZ:</label>
                <inputType>int</inputType>
                <defaultValue>12345</defaultValue>
                <Validation>
                    <minValue>10000</minValue>
                    <maxValue>99999</maxValue>
                </Validation>
            </InputFormElement>
            <SelectFormElement id="selectOne2">
                <selectType>one</selectType>
            </SelectFormElement>
        </FormGroup>
    </FormGroup>

    <CodeList id="testCodeList1">
        <Code id="1">
            <value>dataset</value>
            <label>Dataset</label>
        </Code>
        <Code id="2">
            <value>service</value>
            <label>Service</label>
        </Code>
    </CodeList>
    <CodeList id="testCodeList2">
        <Code id="1">
            <value>nummer1</value>
            <label>Nummer 1</label>
        </Code>
        <Code id="2">
            <value>nummer2</value>
            <label>Nummer 2</label>
        </Code>
        <Code id="3">
            <value>nummer3</value>
            <label>Nummer 3</label>
        </Code>
    </CodeList>

</FormConfiguration>

=== 120534/deegree3/deegree-client/deegree-mdeditor/src/main/webapp/WEB-INF/conf/mdeditor/exampleConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!--XML-Beispieldatei von XMLSpy generiert v2008 rel. 2 sp2 (http://www.altova.com)-->
<FormConfiguration xsi:schemaLocation="http://www.deegree.org/igeoportal schema/formConfiguration.xsd"
    xmlns="http://www.deegree.org/igeoportal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <layoutType>tab</layoutType>

    <DatasetConfiguration>
        <identifier>AllgFormGroup/ref</identifier>
        <title>InhFormGroup/titel</title>
        <description>InhFormGroup/description</description>
        <Mapping>
            <mappingURL>isoMapping.xml</mappingURL>
        </Mapping>
    </DatasetConfiguration>

    <FormGroup id="AllgFormGroup">
        <label>AllgFormGroup_l</label>
        <title>AllgFormGroup_t</title>
        <ReferencedFormElement id="ref" required="true">
            <label>AllgFormGroup_ref_l</label>
            <help>AllgFormGroup_ref_h</help>
            <bean-name>generateIdBean</bean-name>
        </ReferencedFormElement>
        <SelectFormElement id="hierarchylevel" visible="true">
            <label>AllgFormGroup_hier_l</label>
            <selectType>one</selectType>
            <referenceToCodeList>hierarchylevel</referenceToCodeList>
        </SelectFormElement>

        <!-- TODO: Elternobjekt -->
        <!--
            <SelectFormElement id="selectOneK" visible="true"> <label>Eltern-Objekt:</label>
            <selectType>one</selectType> <referenceToGroup></referenceToGroup> </SelectFormElement>
        -->

        <SelectFormElement id="contactMD" visible="true">
            <label>AllgFormGroup_contact_l</label>
            <selectType>one</selectType>
            <referenceToGroup>ContactFormGroup</referenceToGroup>
            <referenceText>Name: ${KtextName}</referenceText>
        </SelectFormElement>
    </FormGroup>

    <FormGroup id="InhFormGroup">
        <label>InhFormGroup_l</label>
        <title>InhFormGroup_t</title>
        <InputFormElement id="title" required="true">
            <label>InhFormGroup_title_l</label>
            <help>InhFormGroup_title_h</help>
            <inputType>text</inputType>
        </InputFormElement>
        <InputFormElement id="description" required="true">
            <label>InhFormGroup_desc_l</label>
            <help>InhFormGroup_desc_h</help>
            <inputType>textarea</inputType>
        </InputFormElement>
        <SelectFormElement id="theme" visible="true">
            <label>InhFormGroup_theme_l</label>
            <help>InhFormGroup_theme_h</help>
            <selectType>one</selectType>
            <referenceToCodeList>topicCategory</referenceToCodeList>
        </SelectFormElement>
        <SelectFormElement id="keywords" visible="true">
            <label>InhFormGroup_keywords_l</label>
            <selectType>many</selectType>
            <referenceToCodeList>keyword</referenceToCodeList>
        </SelectFormElement>
        <InputFormElement id="origin">
            <label>InhFormGroup_origin_l</label>
            <inputType>textarea</inputType>
        </InputFormElement>
        <!--
            <InputFormElement id="lenght"> <label>InhFormGroup_lengh_l</label> <inputType>text</inputType> <Validation>
            <length>10</length> </Validation> </InputFormElement> <InputFormElement id="date"> <label>Datum:</label>
            <inputType>timestamp</inputType> </InputFormElement> <InputFormElement id="range"> <label>Range:</label>
            <inputType>int</inputType> <Validation> <minValue>10</minValue> <maxValue>99</maxValue> </Validation>
            </InputFormElement> <SelectFormElement id="contactData" visible="true"> <label>Zuständige Stelle/Person
            (Daten):</label> <selectType>one</selectType> <referenceToGroup>ContactFormGroup</referenceToGroup>
            </SelectFormElement> </FormGroup>
        -->
        <!--
            <InputFormElement id="ganzzahl1"> <label>int größer 23:</label> <inputType>int</inputType> <Validation>
            <minValue>23</minValue> </Validation> </InputFormElement> <InputFormElement id="ganzzahl2"> <label> int
            größer 23, kleiner 27:</label> <inputType>int</inputType> <Validation> <minValue>23</minValue>
            <maxValue>27</maxValue> </Validation> </InputFormElement> <InputFormElement id="ganzzahl3"> <label> int
            kleiner 27:</label> <inputType>int</inputType> <Validation> <maxValue>27</maxValue> </Validation>
            </InputFormElement> <InputFormElement id="fließzahl1"> <label>double größer 23:</label>
            <inputType>double</inputType> <Validation> <minValue>23</minValue> </Validation> </InputFormElement>
            <InputFormElement id="fließzahl2"> <label>double größer 23, kleiner 27:</label>
            <inputType>double</inputType> <Validation> <minValue>23</minValue> <maxValue>27</maxValue> </Validation>
            </InputFormElement> <InputFormElement id="fließzahl3"> <label>double kleiner 27:</label>
            <inputType>double</inputType> <Validation> <maxValue>27</maxValue> </Validation> </InputFormElement>
            <InputFormElement id="text"> <label>text max 2:</label> <inputType>text</inputType> <Validation>
            <length>2</length> </Validation> </InputFormElement>
        -->
    </FormGroup>

    <FormGroup id="SpatialFormGroup">
        <label>SpatialFormGroup_l</label>
        <title>SpatialFormGroup_t</title>
        <SelectFormElement id="country">
            <label>SpatialFormGroup_country_t</label>
            <selectType>one</selectType>
            <referenceToCodeList>countries</referenceToCodeList>
        </SelectFormElement>
    </FormGroup>

    <FormGroup id="TimeFormGroup">
        <label>TimeFormGroup_l</label>
        <title>TimeFormGroup_t</title>
        <InputFormElement id="creation">
            <label>TimeFormGroup_creation_l</label>
            <inputType>timestamp</inputType>
        </InputFormElement>
        <InputFormElement id="publication">
            <label>TimeFormGroup_pub_l</label>
            <inputType>timestamp</inputType>
        </InputFormElement>
        <InputFormElement id="modified">
            <label>TimeFormGroup_mod_l</label>
            <inputType>timestamp</inputType>
        </InputFormElement>
        <FormGroup id="TimePeriodFormGroup">
            <title>TimeFormGroup_per_t</title>
            <InputFormElement id="begin">
                <label>TimeFormGroup_per_beg_l</label>
                <inputType>timestamp</inputType>
            </InputFormElement>
            <InputFormElement id="end">
                <label>TimeFormGroup_per_end_l</label>
                <inputType>timestamp</inputType>
            </InputFormElement>
        </FormGroup>
    </FormGroup>


    <FormGroup id="FormatFormGroup" occurence="unbounded">
        <label>FormatFormGroup_l</label>
        <title>FormatFormGroup_t</title>
        <InputFormElement id="Formatname">
            <label>FormatFormGroup_name_l</label>
            <help>FormatFormGroup_name_h</help>
            <inputType>text</inputType>
        </InputFormElement>
        <InputFormElement id="FormatVersion">
            <label>FormatFormGroup_vers_l</label>
            <help>FormatFormGroup_vers_h</help>
            <inputType>text</inputType>
        </InputFormElement>
    </FormGroup>

</FormConfiguration>
