=== 120534/deegree3/deegree-services/src/main/resources/META-INF/schemas/wms/3.1.0/wms_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:wms="http://www.deegree.org/services/wms" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.deegree.org/services/wms" elementFormDefault="qualified" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  jaxb:version="2.1">

  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.services.jaxb.wms" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>

  <!--  copied from commons: -->
  <!-- =========================================================== -->
  <element name="ScaleDenominators" type="wms:ScaleDenominatorsType" />
  <!-- =========================================================== -->
  <complexType name="ScaleDenominatorsType">
    <annotation>
      <documentation>
        The scale denominators define the map resolution to
        which the datasets are valid. TODO define exact
        value calculation here!
      </documentation>
    </annotation>
    <attribute name="min" type="double" use="required" />
    <attribute name="max" type="double" use="required" />
    <attribute name="native" type="double" use="optional" />
  </complexType>
  <!-- ========================================================== -->
  <element name="BoundingBox" type="wms:BoundingBoxType" />
  <!-- =========================================================== -->
  <complexType name="BoundingBoxType">
    <annotation>
      <documentation>XML encoded minimum rectangular bounding box (or
        region) parameter, surrounding all the associated
        data.</documentation>
      <documentation>
        This type is adapted from the EnvelopeType of GML 3.1,
        with modified contents and documentation for
        encoding a MINIMUM size box
        SURROUNDING
        all associated data.
      </documentation>
    </annotation>
    <sequence>
      <element name="LowerCorner" type="wms:PositionType">
        <annotation>
          <documentation>
            Position of the bounding box corner at which the
            value of each coordinate normally is the
            algebraic minimum within
            this bounding box. In
            some cases, this position is normally displayed
            at the top, such
            as the top left for some image coordinates. For
            more information, see
            Subclauses 10.2.5 and C.13.
          </documentation>
        </annotation>
      </element>
      <element name="UpperCorner" type="wms:PositionType">
        <annotation>
          <documentation>
            Position of the bounding box corner at which the
            value of each coordinate normally is the
            algebraic maximum within
            this bounding box. In
            some cases, this position is normally displayed
            at the bottom,
            such as the bottom right for some image coordinates.
            For more information,
            see Subclauses 10.2.5 and C.13.
          </documentation>
        </annotation>
      </element>
    </sequence>
    <attribute name="crs" type="anyURI" use="optional">
      <annotation>
        <documentation>
          Usually references the definition of a CRS, as
          specified in [OGC Topic 2]. Such a CRS definition
          can be XML encoded
          using the
          gml:CoordinateReferenceSystemType in [GML 3.1]. For well
          known references, it is not
          required that a CRS definition exist at
          the location
          the URI points to. If no anyURI value is included, the
          applicable CRS must be either: a) Specified outside the bounding box,
          but inside a
          data structure that includes
          this bounding box, as
          specified for a specific OWS use of this bounding box type. b) Fixed
          and specified in the
          Implementation Specification for a specific OWS
          use of the bounding box type.
        </documentation>
      </annotation>
    </attribute>
    <attribute name="dimensions" type="int" use="optional">
      <annotation>
        <documentation>
          The number of dimensions in this CRS (the length of a
          coordinate sequence in this use of the
          PositionType). This number is
          specified by the
          CRS definition, but can also be specified here.
        </documentation>
      </annotation>
    </attribute>
  </complexType>
  <simpleType name="PositionType">
    <annotation>
      <documentation>
        Position instances hold the coordinates of a position in
        a coordinate reference system (CRS)
        referenced by the related "crs"
        attribute or
        elsewhere. For an angular coordinate axis that is physically
        continuous for multiple revolutions, but whose recorded values can be
        discontinuous, special conditions apply
        when the bounding box is
        continuous across the value discontinuity: a) If the bounding box is
        continuous clear
        around this angular axis, then ordinate values of minus
        and plus infinity shall be used. b) If the bounding box
        is continuous
        across the value discontinuity but is not continuous clear around this
        angular axis, then some
        non-normal value can be used if specified for a
        specific OWS use of the BoundingBoxType. For more information,
        see
        Subclauses 10.2.5 and C.13.
      </documentation>
      <documentation>
        This type is adapted from DirectPositionType and
        doubleList of GML 3.1. The adaptations include
        omission of all the
        attributes, since the
        needed information is included in the
        BoundingBoxType.
      </documentation>
    </annotation>
    <list itemType="double" />
  </simpleType>
  <!-- end copied from commons -->

  <element name="deegreeWMS">
    <complexType>
      <sequence>
        <element name="SupportedVersions" minOccurs="0">
          <complexType>
            <sequence>
              <element name="Version" type="wms:WMSVersionType" maxOccurs="unbounded" />
            </sequence>
          </complexType>
        </element>
        <element name="ServiceConfiguration" type="wms:ServiceConfigurationType" />
        <element name="FeatureInfoFormats" minOccurs="0" type="wms:FeatureInfoFormatsType" />
      </sequence>
      <attribute name="configVersion" use="required" type="wms:ConfigVersionType" />
    </complexType>
  </element>

  <complexType name="ServiceConfigurationType">
    <sequence>
      <element name="DefaultLayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
      <element ref="wms:AbstractLayer" minOccurs="0" />
    </sequence>
  </complexType>

  <complexType name="FeatureInfoFormatsType">
    <sequence>
      <element name="GetFeatureInfoFormat" minOccurs="0" maxOccurs="unbounded">
        <complexType>
          <sequence>
            <element name="File" type="string" />
            <element name="Format" type="string" />
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <complexType name="LayerOptionsType">
    <sequence>
      <element name="AntiAliasing" type="string" minOccurs="0" />
      <element name="RenderingQuality" type="string" minOccurs="0" />
      <element name="Interpolation" type="string" minOccurs="0" />
      <element name="MaxFeatures" type="int" minOccurs="0" />
      <element name="FeatureInfoRadius" type="int" minOccurs="0" />
    </sequence>
  </complexType>

  <complexType name="BaseAbstractLayerType" />

  <element name="AbstractLayer" type="wms:BaseAbstractLayerType" abstract="true" />

  <complexType name="DirectStyleType">
    <sequence>
      <element name="File" type="string" />
      <element name="Name" type="string" minOccurs="0" />
      <element name="LegendConfigurationFile" type="string" minOccurs="0" />
    </sequence>
  </complexType>

  <complexType name="SLDStyleType">
    <sequence>
      <element name="File" type="string" />
      <element name="NamedLayer" type="string" />
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element name="Name" type="string" minOccurs="0" />
        <element name="UserStyle" type="string" />
        <element name="LegendConfigurationFile" type="string" minOccurs="0" />
      </sequence>
    </sequence>
  </complexType>

  <complexType name="DimensionType">
    <sequence>
      <element name="Name" type="string" minOccurs="0" />
      <element name="Property" type="QName" />
      <element name="DefaultValue" type="string" minOccurs="0" />
      <element name="MultipleValues" type="boolean" default="0" minOccurs="0" />
      <element name="NearestValue" type="boolean" default="0" minOccurs="0" />
      <element name="Current" type="boolean" default="0" minOccurs="0" />
      <element name="Units" type="string" minOccurs="0" />
      <element name="UnitSymbol" type="string" minOccurs="0" />
      <element name="Extent" type="string" />
    </sequence>
    <attribute name="isTime" type="boolean" use="optional" default="false" />
    <attribute name="isElevation" type="boolean" use="optional" default="false" />
  </complexType>

  <complexType name="AbstractLayerType">
    <complexContent>
      <extension base="wms:BaseAbstractLayerType">
        <sequence>
          <element name="Name" type="string" minOccurs="0" />
          <element name="Title" type="string" minOccurs="0" />
          <element name="Abstract" type="string" minOccurs="0" />
          <element ref="wms:Keywords" minOccurs="0" />
          <element ref="wms:BoundingBox" minOccurs="0" />
          <element name="CRS" type="string" minOccurs="0" />
          <element name="Dimension" type="wms:DimensionType" minOccurs="0" maxOccurs="unbounded" />
          <choice>
            <element ref="wms:ScaleDenominators" minOccurs="0" />
            <element name="ScaleUntil" type="double" minOccurs="0" />
            <element name="ScaleAbove" type="double" minOccurs="0" />
          </choice>
          <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
          <choice minOccurs="0">
            <element name="FeatureStoreId" type="string" />
            <element name="CoverageStoreId" type="string" />
            <element name="RemoteWMSStoreId" type="string" />
          </choice>
          <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
          <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
          <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
        </sequence>
        <attribute name="queryable" type="boolean" use="optional" />
      </extension>
    </complexContent>
  </complexType>

  <element name="RequestableLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <restriction base="wms:AbstractLayerType">
          <sequence>
            <element name="Name" type="string" />
            <element name="Title" type="string" />
            <element name="Abstract" type="string" minOccurs="0" />
            <element ref="wms:Keywords" minOccurs="0" />
            <element ref="wms:BoundingBox" minOccurs="0" />
            <element name="CRS" type="string" minOccurs="0" />
            <element name="Dimension" type="wms:DimensionType" minOccurs="0" maxOccurs="unbounded" />
            <choice>
              <element ref="wms:ScaleDenominators" minOccurs="0" />
              <element name="ScaleUntil" type="double" minOccurs="0" />
              <element name="ScaleAbove" type="double" minOccurs="0" />
            </choice>
            <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0">
              <element name="FeatureStoreId" type="string" />
              <element name="CoverageStoreId" type="string" />
              <element name="RemoteWMSStoreId" type="string" />
            </choice>
            <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
          </sequence>
          <attribute name="queryable" type="boolean" use="optional" />
        </restriction>
      </complexContent>
    </complexType>
  </element>

  <element name="UnrequestableLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <restriction base="wms:AbstractLayerType">
          <sequence>
            <element name="Title" type="string" />
            <element name="Abstract" type="string" minOccurs="0" />
            <element ref="wms:Keywords" minOccurs="0" />
            <element ref="wms:BoundingBox" minOccurs="0" />
            <element name="CRS" type="string" minOccurs="0" />
            <choice>
              <element ref="wms:ScaleDenominators" minOccurs="0" />
              <element name="ScaleUntil" type="double" minOccurs="0" />
              <element name="ScaleAbove" type="double" minOccurs="0" />
            </choice>
            <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0">
              <element name="FeatureStoreId" type="string" />
              <element name="CoverageStoreId" type="string" />
              <element name="RemoteWMSStoreId" type="string" />
            </choice>
            <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
          </sequence>
          <attribute name="queryable" type="boolean" use="optional" />
        </restriction>
      </complexContent>
    </complexType>
  </element>

  <element name="LogicalLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <restriction base="wms:AbstractLayerType">
          <sequence>
            <element ref="wms:BoundingBox" minOccurs="0" />
            <choice>
              <element ref="wms:ScaleDenominators" minOccurs="0" />
              <element name="ScaleUntil" type="double" minOccurs="0" />
              <element name="ScaleAbove" type="double" minOccurs="0" />
            </choice>
            <element ref="wms:AbstractLayer" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0">
              <element name="FeatureStoreId" type="string" />
              <element name="CoverageStoreId" type="string" />
              <element name="RemoteWMSStoreId" type="string" />
            </choice>
            <element name="DirectStyle" type="wms:DirectStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="SLDStyle" type="wms:SLDStyleType" minOccurs="0" maxOccurs="unbounded" />
            <element name="LayerOptions" type="wms:LayerOptionsType" minOccurs="0" />
          </sequence>
          <attribute name="queryable" type="boolean" use="optional" />
        </restriction>
      </complexContent>
    </complexType>
  </element>

  <element name="DynamicLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <extension base="wms:BaseAbstractLayerType">
          <choice>
            <element name="ShapefileDirectory" type="string" />
            <element name="PostGIS" type="string" />
          </choice>
        </extension>
      </complexContent>
    </complexType>
  </element>

  <element name="StatisticsLayer" substitutionGroup="wms:AbstractLayer">
    <complexType>
      <complexContent>
        <extension base="wms:BaseAbstractLayerType" />
      </complexContent>
    </complexType>
  </element>

  <simpleType name="WMSVersionType">
    <restriction base="string">
      <enumeration value="1.1.1" />
      <enumeration value="1.3.0" />
      <!-- enumeration value="2.0.0" / -->
    </restriction>
  </simpleType>

  <!-- ========================================================== -->
  <element name="Keywords" type="wms:KeywordsType" />
  <!-- ========================================================== -->
  <complexType name="KeywordsType">
    <annotation>
      <documentation>
        Unordered list of one or more commonly used or formalised word(s) or phrase(s) used to describe
        the
        subject. When needed, the optional "type" can name the type of the associated list of keywords that shall
        all
        have the same type. Also when needed, the codeSpace attribute of that "type" can reference the type name
        authority and/or thesaurus. If the xml:lang attribute is not included in a Keyword element, then no language is
        specified for that element unless specified by another means. All Keyword elements in the same Keywords element
        that share the same xml:lang attribute value represent different keywords in that language.
      </documentation>
      <documentation>
        For OWS use, the optional thesaurusName element was omitted as being complex information that
        could
        be referenced by the codeSpace attribute of the Type element.
      </documentation>
    </annotation>
    <sequence>
      <element name="Keyword" type="wms:LanguageStringType" maxOccurs="unbounded" />
      <element name="Type" type="wms:CodeType" minOccurs="0" />
    </sequence>
  </complexType>
  <complexType name="LanguageStringType">
    <annotation>
      <documentation>
        Text string with the language of the string identified as recommended in the XML 1.0 W3C
        Recommendation, section 2.12.
      </documentation>
    </annotation>
    <simpleContent>
      <extension base="string">
        <attribute name="lang" type="string" use="optional" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="CodeType">
    <annotation>
      <documentation>
        Name or code with an (optional) authority. If the codeSpace attribute is present, its value shall
        reference a dictionary, thesaurus, or authority for the name or code, such as the organisation who assigned the
        value, or the dictionary from which it is taken.
      </documentation>
      <documentation>
        Type copied from basicTypes.xsd of GML 3 with documentation edited, for possible use outside the
        ServiceIdentification section of a service metadata document.
      </documentation>
    </annotation>
    <simpleContent>
      <extension base="string">
        <attribute name="codeSpace" type="anyURI" use="optional" />
      </extension>
    </simpleContent>
  </complexType>

  <simpleType name="ConfigVersionType">
    <restriction base="string">
      <enumeration value="3.0.0" />
      <enumeration value="3.1.0" />
    </restriction>
  </simpleType>

</schema>

=== 120534/deegree3/deegree-test/deegree-wms-cite111/src/main/webapp/WEB-INF/conf/services/wms.xml
<?xml version="1.0" encoding="UTF-8"?>
<deegreeWMS configVersion="0.5.0" xmlns="http://www.deegree.org/services/wms" xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dgws="http://www.deegree.org/webservices"
  xsi:schemaLocation="http://www.deegree.org/services/wms http://schemas.deegree.org/wms/0.5.0/wms_configuration.xsd">

  <ServiceConfiguration>

    <RequestableLayer>
      <Name>root</Name>
      <Title>My Root Layer</Title>
      <CRS>EPSG:4326</CRS>

      <RequestableLayer>
        <Name>cite:BasicPolygons</Name>
        <Title>cite:BasicPolygons</Title>
        <FeatureStoreId>basicpolygons</FeatureStoreId>
        <DirectStyle>
          <File>../styles/BasicPolygons.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:Forests</Name>
        <Title>cite:Forests</Title>
        <FeatureStoreId>forests</FeatureStoreId>
        <DirectStyle>
          <File>../styles/Forests.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:Lakes</Name>
        <Title>cite:Lakes</Title>
        <Dimension isElevation="true">
          <Property>ELEV</Property>
          <DefaultValue>500</DefaultValue>
          <NearestValue>true</NearestValue>
          <Extent>500,490,480</Extent>
        </Dimension>
        <FeatureStoreId>lakes</FeatureStoreId>
        <DirectStyle>
          <File>../styles/Lakes.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:Ponds</Name>
        <Title>cite:Ponds</Title>
        <FeatureStoreId>ponds</FeatureStoreId>
        <DirectStyle>
          <File>../styles/Ponds.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:NamedPlaces</Name>
        <Title>cite:NamedPlaces</Title>
        <FeatureStoreId>namedplaces</FeatureStoreId>
        <DirectStyle>
          <File>../styles/NamedPlaces.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:Buildings</Name>
        <Title>cite:Buildings</Title>
        <FeatureStoreId>buildings</FeatureStoreId>
        <DirectStyle>
          <File>../styles/Buildings.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:BuildingCenters</Name>
        <Title>cite:BuildingCenters</Title>
        <FeatureStoreId>buildingcenters</FeatureStoreId>
        <DirectStyle>
          <File>../styles/BuildingCenters.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:DividedRoutes</Name>
        <Title>cite:DividedRoutes</Title>
        <FeatureStoreId>dividedroutes</FeatureStoreId>
        <DirectStyle>
          <File>../styles/DividedRoutes.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:RoadSegments</Name>
        <Title>cite:RoadSegments</Title>
        <FeatureStoreId>roadsegments</FeatureStoreId>
        <DirectStyle>
          <File>../styles/RoadSegments.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:MapNeatline</Name>
        <Title>cite:MapNeatline</Title>
        <FeatureStoreId>mapneatline</FeatureStoreId>
        <DirectStyle>
          <File>../styles/MapNeatline.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:Streams</Name>
        <Title>cite:Streams</Title>
        <FeatureStoreId>streams</FeatureStoreId>
        <DirectStyle>
          <File>../styles/Streams.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:Bridges</Name>
        <Title>cite:Bridges</Title>
        <FeatureStoreId>bridges</FeatureStoreId>
        <DirectStyle>
          <File>../styles/Bridges.xml</File>
        </DirectStyle>
      </RequestableLayer>

      <RequestableLayer>
        <Name>cite:Autos</Name>
        <Title>cite:Autos</Title>
        <Dimension isTime="true">
          <Property>TIME</Property>
          <MultipleValues>true</MultipleValues>
          <NearestValue>true</NearestValue>
          <Current>true</Current>
          <Extent>2000-01-01T00:00:00Z/2000-01-01T00:01:00Z/PT5S</Extent>
        </Dimension>
        <FeatureStoreId>autos</FeatureStoreId>
        <DirectStyle>
          <File>../styles/Autos.xml</File>
        </DirectStyle>
      </RequestableLayer>

    </RequestableLayer>

  </ServiceConfiguration>

  <PublishedInformation>
    <SupportedVersions>
      <Version>1.1.1</Version>
    </SupportedVersions>
  </PublishedInformation>

</deegreeWMS>
